version: '3.3'
services:
    nifi:
        container_name: nifidev
        image: apache/nifi:1.9.1
        user: root 
        volumes:
                - /opt/certs:/opt/certs
        ports:
                - 8443:8443 # Unsecured HTTP Web Port
        environment:
            - AUTH=SIMPLE
            - KEYSTORE_PATH=/opt/certs/keystore.jks
            - KEYSTORE_TYPE=JKS
            - KEYSTORE_PASSWORD=123456
            - TRUSTSTORE_PATH=/opt/certs/truststore.jks
            - TRUSTSTORE_PASSWORD=123456
            - TRUSTSTORE_TYPE=JKS
            - INITIAL_ADMIN_IDENTITY=''
            - LDAP_AUTHENTICATION_STRATEGY='SIMPLE' 
            - LDAP_MANAGER_DN=''
            - LDAP_MANAGER_PASSWORD=''
            - LDAP_USER_SEARCH_BASE=''
            - LDAP_USER_SEARCH_FILTER='cn={0}'
            - LDAP_IDENTITY_STRATEGY='USE_USERNAME'
            - LDAP_URL=''
            - TZ=America/Sao_Paulo
