version: '3.3'
services:
    nifi:
        container_name: nifilab
        image: apache/nifi:1.9.1
        user: root 
        volumes:
                - /home/starlord/Documents/Projetos/NiFI/docker/certs:/opt/certs
        ports:
                - 8443:8443 # Unsecured HTTP Web Port
        environment:
            - AUTH=SIMPLE
            - KEYSTORE_PATH=/opt/certs/keystore.jks
            - KEYSTORE_TYPE=JKS
            - KEYSTORE_PASSWORD=123456
            - TRUSTSTORE_PATH=/opt/certs/truststore.jks
            - TRUSTSTORE_PASSWORD=123456
            - TRUSTSTORE_TYPE=JKS
            - INITIAL_ADMIN_IDENTITY='welington.andrade'
            - LDAP_AUTHENTICATION_STRATEGY='SIMPLE' 
            - LDAP_MANAGER_DN='CN=nifi,CN=Users,DC=netmaster,DC=intra'
            - LDAP_MANAGER_PASSWORD='N1fi123'
            - LDAP_USER_SEARCH_BASE='DC=netmaster,DC=intra'
            - LDAP_USER_SEARCH_FILTER='cn={0}'
            - LDAP_IDENTITY_STRATEGY='USE_USERNAME'
            - LDAP_URL='ldap://luckman01.netmaster.intra:389'
            - TZ=America/Sao_Paulo
